# Generated by Django 4.2 on 2024-02-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_news_category_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
